### ISSUE TITLE
Unable to locate package io.elementary.monitor

### ISSUE THREAD

**Issue by doobes** [elementary/monitor#400]
### What Happened?

sudo add-apt-repository ppa:stsdc/monitor -> ok

sudo apt install io.elementary.monitor ->

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package io.elementary.monitor
E: Couldn't find any package by glob 'io.elementary.monitor
```
Where is it?

### Steps to Reproduce

sudo add-apt-repository ppa:stsdc/monitor -> ok

sudo apt install io.elementary.monitor ->

### Expected Behavior

App is found and installed

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by stsdc** [comment]
Please use "sudo apt install com.github.stsdc.monitor`.

We are in a process of moving to official PPA.

**Comment by stsdc** [comment]
Readme got an update to avoid confusion.
