### ISSUE TITLE
CPU-Temperature no settings

### ISSUE THREAD

**Issue by sapeg** [elementary/monitor#406]
There is such an application for Elementary OS : https://github.com/stsdc/monitor. It uses information from: /sys/class/hwmon/hwmon0,  to display information about the processor temperature.  But there is no information about it in this catalog. Maybe there is some other place where this information is stored?

**Comment by stsdc** [comment]
Please elaborate what  settings Monitor is lacking?

**Comment by sapeg** [comment]
> Please elaborate what settings Monitor is lacking?

it is no longer relevant
